repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        types: [shell]

  # Terraform
  - repo: local
    hooks:
      - id: tf-format
        name: terraform format
        entry: make -s _ops.lint.tf.format
        language: system
        types_or: [hcl, terraform]
        require_serial: true
      - id: tf-hcl-validate
        name: terragrunt hcl validate
        entry: make -s _ops.lint.tf.hcl.validate
        language: system
        types_or: [hcl, terraform]
        require_serial: true
      - id: tf-docs
        name: terraform docs
        entry: make -s _ops.lint.tf.docs
        language: system
        types_or: [hcl, terraform]
        require_serial: true

  # Code scanning
  - repo: local
    hooks:
      - id: noop
        name: No-op hook
        entry: echo "noop"
        language: system
        always_run: true
        pass_filenames: false
