repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: '^(src/tf/.*README.md$)'
      - id: forbid-new-submodules
      - id: trailing-whitespace

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        name: shellcheck
        types: [shell]

  # Terraform
  - repo: local
    hooks:
      - id: tf-format
        name: terraform format
        entry: make -s _ops.tf.lint.format
        language: system
        types_or: [hcl, terraform]
        require_serial: true
      - id: tf-docs
        name: terraform docs
        entry: make -s _ops.tf.lint.docs
        language: system
        types_or: [hcl, terraform]
        require_serial: true

  # Vulnerability scanning
  - repo: local
    hooks:
      - id: code-scan
        name: code scan
        entry: make -s ops.scan
        language: system
        always_run: true
        require_serial: true
        verbose: true
