name: Deploy
on:
  push:
    tags:
      - 'v*.*.*'   # Match semantic version release.
      - 'v*.*.*-*' # Match pre-release, eg. v1.2.0-rc.1, v1.2.3-beta.1

permissions:
  actions: read
  contents: write
  packages: write

env:
  NAMESPACE: ocp
  SERVICE: project
  GHCR_REGISTRY: ghcr.io
  GHCR_OWNER: ${{ github.repository_owner }}
  SEMVER: ${{ github.ref_name }}

jobs:
  metadata:
    name: 'Metadata'
    runs-on: ubuntu-latest
    outputs:
      green: ${{ steps.last-successful-commit.outputs.base }}
      image-prefix: ${{ steps.set-image-prefix.outputs.image_prefix  }}
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - id: last-successful-commit
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: main
          workflow-id: 'deploy.yml'

      - id: set-image-prefix
        run: |
          IMAGE_PREFIX="${GHCR_REGISTRY}/${GHCR_OWNER}/${NAMESPACE}.${SERVICE}"
          echo "image_prefix=$IMAGE_PREFIX" >> $GITHUB_OUTPUT

      - id: set-version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  push_generate_image:
    name: 'Push ocp.project.generate'
    runs-on: ubuntu-latest
    needs: metadata
    outputs:
      changed: ${{ steps.changed-image.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - id: changed-image
        uses: tj-actions/changed-files@v47
        with:
          base_sha: ${{ needs.metadata.outputs.green }}
          files: ./src/docker/Dockerfile.generate

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/docker/Dockerfile.generate
          load: false
          push: true
          cache-from: |
            type=gha,scope=terraform.generate
          cache-to: |
            type=gha,scope=terraform.generate,mode=max
          target: generate
          tags: |
            ${{ needs.metadata.outputs.image-prefix }}.generate:${{ needs.metadata.outputs.version }}
            ${{ needs.metadata.outputs.image-prefix }}.generate:${{ github.sha }}
            ${{ needs.metadata.outputs.image-prefix }}.generate:latest

  push_terraform_lint_image:
    name: 'Push ocp.project.tf.lint'
    runs-on: ubuntu-latest
    needs: metadata
    outputs:
      changed: ${{ steps.changed-image.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - id: changed-image
        uses: tj-actions/changed-files@v47
        with:
          base_sha: ${{ needs.metadata.outputs.green }}
          files: ./src/docker/Dockerfile.tf.lint

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/docker/Dockerfile.tf.lint
          load: false
          push: true
          cache-from: |
            type=gha,scope=terraform.linters
          cache-to: |
            type=gha,scope=terraform.linters,mode=max
          target: linters
          tags: |
            ${{ needs.metadata.outputs.image-prefix }}.tf.lint:${{ needs.metadata.outputs.version }}
            ${{ needs.metadata.outputs.image-prefix }}.tf.lint:${{ github.sha }}
            ${{ needs.metadata.outputs.image-prefix }}.tf.lint:latest

  push_terraform_image:
    name: 'Push ocp.project.tf'
    runs-on: ubuntu-latest
    needs: metadata
    outputs:
      changed: ${{ steps.changed-image.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - id: changed-image
        uses: tj-actions/changed-files@v47
        with:
          base_sha: ${{ needs.metadata.outputs.green }}
          files: ./src/docker/Dockerfile.tf

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/docker/Dockerfile.tf
          load: false
          push: true
          cache-from: |
            type=gha,scope=terraform.tf
          cache-to: |
            type=gha,scope=terraform.tf,mode=max
          target: tf
          tags: |
            ${{ needs.metadata.outputs.image-prefix }}.tf:${{ needs.metadata.outputs.version }}
            ${{ needs.metadata.outputs.image-prefix }}.tf:${{ github.sha }}
            ${{ needs.metadata.outputs.image-prefix }}.tf:latest

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [
      metadata,
      push_generate_image,
      push_terraform_lint_image,
      push_terraform_image,
    ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: 'Save image tags'
        run: |
          prefix="${{ needs.metadata.outputs.image-prefix }}"
          tags_file="docker-tags.txt"

          images=(
            'generate'
            'tf.lint'
            'tf'
          )

          for image in "${images[@]}"; do
            echo "${prefix}.${image}:${{ needs.metadata.outputs.version }}" >> "${tags_file}"
            echo "${prefix}.${image}:${{ github.sha }}" >> "${tags_file}"
            echo "${prefix}.${image}:latest" >> "${tags_file}"
          done

      - uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.SEMVER }}
          tag_name: ${{ env.SEMVER }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          prerelease: ${{ contains(env.SEMVER, '-') }}
          files: |
            docker-tags.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
