name: Deploy
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  actions: read
  contents: read
  packages: write

env:
  NAMESPACE: ocp
  SERVICE: project
  GHCR_REGISTRY: ghcr.io
  GHCR_OWNER: ${{ github.repository_owner }}

jobs:
  change_detection:
    name: 'Detect changes'
    runs-on: ubuntu-latest
    outputs:
      green: ${{ steps.last-successful-commit.outputs.base }}
      images: ${{ steps.changed-images.outputs.any_changed }}
      tf-modules: ${{ steps.changed-tf-modules.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - id: last-successful-commit
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
          workflow-id: 'integrate.yml'

      - id: changed-images
        uses: tj-actions/changed-files@v47
        with:
          base_sha: ${{ steps.last-successful-commit.outputs.base }}
          files: src/docker/**Dockerfile.*

      - id: changed-tf-modules
        uses: tj-actions/changed-files@v47
        with:
          base_sha: ${{ steps.last-successful-commit.outputs.base }}
          files: src/tf/modules/**/*.{tf,hcl}

      - name: Set image prefix
        run: |
          IMAGE_PREFIX="${GHCR_REGISTRY}/${GHCR_OWNER}/${NAMESPACE}.${SERVICE}"
          echo "IMAGE_PREFIX=$IMAGE_PREFIX" >> $GITHUB_ENVt

  push_terraform_lint_image:
    name: 'Push ocp.project.tf.lint'
    runs-on: ubuntu-latest
    needs: change_detection
    if: needs.change_detection.outputs.green == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - id: changed-image
        uses: tj-actions/changed-files@v47
        with:
          base_sha: ${{ needs.change_detection.outputs.green }}
          files: src/docker/Dockerfile.tf.lint

      - uses: docker/login-action@v2
        if: steps.changed-image.outputs.any_changed == 'true'
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3
        if: steps.changed-image.outputs.any_changed == 'true'

      - uses: docker/build-push-action@v6
        if: steps.changed-image.outputs.any_changed == 'true'
        with:
          context: .
          file: src/docker/Dockerfile.tf.lint
          load: false
          push: true
          cache-from: |
            type=gha,scope=terraform.linters
          cache-to: |
            type=gha,scope=terraform.linters,mode=max
          target: linters
          tags: |
            ${{ env.IMAGE_PREFIX }}.tf.lint:latest
            ${{ env.IMAGE_PREFIX }}.tf.lint:${{ github.sha }}
            ${{ env.IMAGE_PREFIX }}.tf.lint:${{ env.SEMVER }}

  push_terraform_image:
    name: 'Push ocp.project.tf'
    runs-on: ubuntu-latest
    needs: change_detection
    if: needs.change_detection.outputs.green == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - id: changed-image
        uses: tj-actions/changed-files@v47
        with:
          base_sha: ${{ needs.change_detection.outputs.green }}
          files: src/docker/Dockerfile.tf

      - uses: docker/setup-buildx-action@v3
        if: steps.changed-image.outputs.any_changed == 'true'

      - uses: docker/login-action@v2
        if: steps.changed-image.outputs.any_changed == 'true'
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        if: steps.changed-image.outputs.any_changed == 'true'
        with:
          context: .
          file: src/docker/Dockerfile.tf
          load: false
          push: true
          cache-from: |
            type=gha,scope=terraform.tf
          cache-to: |
            type=gha,scope=terraform.tf,mode=max
          target: tf
          tags: |
            ${{ env.IMAGE_PREFIX }}.tf:latest
            ${{ env.IMAGE_PREFIX }}.tf:${{ github.sha }}
            ${{ env.IMAGE_PREFIX }}.tf:${{ env.SEMVER }}

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [push_terraform_lint_image, push_terraform_image]
    steps:
      - uses: actions/checkout@v4

      - name: 'Save image tags'
        run: |
          echo "${{ env.IMAGE_PREFIX }}.tf.lint:latest" >> docker-tags.txt
          echo "${{ env.IMAGE_PREFIX }}.tf.lint:${{ github.sha }}" >> docker-tags.txt
          echo "${{ env.IMAGE_PREFIX }}.tf.lint:${{ env.SEMVER }}" >> docker-tags.txt
          echo "${{ env.IMAGE_PREFIX }}.tf:latest" >> docker-tags.txt
          echo "${{ env.IMAGE_PREFIX }}.tf:${{ github.sha }}" >> docker-tags.txt
          echo "${{ env.IMAGE_PREFIX }}.tf:${{ env.SEMVER }}" >> docker-tags.txt

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.SEMVER }}
          name: Release ${{ env.SEMVER }}
          files: docker-tags.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
