name: Integrate
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  checks: write
  contents: read

env:
  NAMESPACE: ocp
  SERVICE: project
  GHCR_REGISTRY: ghcr.io
  GHCR_OWNER: ${{ github.repository_owner }}

jobs:
  change_detection:
    name: 'Detect changes'
    runs-on: ubuntu-latest
    outputs:
      green: ${{ steps.last-successful-commit.outputs.base }}
      images: ${{ steps.changed-images.outputs.any_changed  }}
      image-prefix: ${{ steps.set-image-prefix.outputs.image_prefix  }}
      tf-modules: ${{ steps.changed-tf-modules.outputs.any_changed  }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - id: last-successful-commit
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
          workflow-id: 'integrate.yml'

      - id: changed-images
        uses: tj-actions/changed-files@v47
        with:
          base_sha: ${{ steps.last-successful-commit.outputs.base }}
          files: src/docker/**Dockerfile.*

      - id: changed-tf-modules
        uses: tj-actions/changed-files@v47
        with:
          base_sha: ${{ steps.last-successful-commit.outputs.base }}
          files: src/tf/modules/**/*.{tf,hcl}

      - id: set-image-prefix
        if: steps.changed-images.outputs.any_changed
        run: |
          IMAGE_PREFIX="${GHCR_REGISTRY}/${GHCR_OWNER}/${NAMESPACE}.${SERVICE}"
          echo "image_prefix=$IMAGE_PREFIX" >> $GITHUB_OUTPUT

  integrate_terraform_lint_image:
    name: 'Integrate ocp.project.tf.lint'
    runs-on: ubuntu-latest
    needs: change_detection
    if: needs.change_detection.outputs.images == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - id: changed-image
        uses: tj-actions/changed-files@v47
        with:
          base_sha: ${{ needs.change_detection.outputs.green }}
          files: src/docker/Dockerfile.tf.lint

      - uses: docker/login-action@v2
        if: steps.changed-image.outputs.any_changed == 'true'
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3
        if: steps.changed-image.outputs.any_changed == 'true'

      - uses: docker/build-push-action@v6
        if: steps.changed-image.outputs.any_changed == 'true'
        with:
          context: .
          file: src/docker/Dockerfile.tf.lint
          load: true
          push: false
          cache-from: |
            type=gha,scope=terraform.linters
          cache-to: |
            type=gha,scope=terraform.linters,mode=max
          target: linters
          tags: |
            ${{ needs.change_detection.outputs.image-prefix }}.tf.lint:${{ github.sha }}

      - uses: aquasecurity/trivy-action@0.28.0
        if: steps.changed-image.outputs.any_changed == 'true'
        with:
          image-ref: ${{ needs.change_detection.outputs.image-prefix }}.tf.lint:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  integrate_terraform_image:
    name: 'Integrate ocp.project.tf'
    runs-on: ubuntu-latest
    needs: change_detection
    if: needs.change_detection.outputs.images == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - id: changed-image
        uses: tj-actions/changed-files@v47
        with:
          base_sha: ${{ needs.change_detection.outputs.green }}
          files: src/docker/Dockerfile.tf

      - uses: docker/login-action@v2
        if: steps.changed-image.outputs.any_changed == 'true'
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3
        if: steps.changed-image.outputs.any_changed == 'true'

      - uses: docker/build-push-action@v6
        if: steps.changed-image.outputs.any_changed == 'true'
        with:
          context: .
          file: src/docker/Dockerfile.tf
          load: true
          push: false
          cache-from: |
            type=gha,scope=terraform.tf
          cache-to: |
            type=gha,scope=terraform.tf,mode=max
          target: tf
          tags: |
            ${{ needs.change_detection.outputs.image-prefix }}.tf:${{ github.sha }}

      - uses: aquasecurity/trivy-action@0.28.0
        if: steps.changed-image.outputs.any_changed == 'true'
        with:
          image-ref: ${{ needs.change_detection.outputs.image-prefix }}.tf:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  integrate_tf:
    name: 'Integrate terraform'
    runs-on: ubuntu-latest
    if: needs.change_detection.outputs.tf-modules == 'true'
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v2
        if: steps.changed-image.outputs.any_changed == 'true'
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: No-op
        run: echo "No steps yet"

      # TODO: Pull the EXISTING tf.lint docker image and use it.
